name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define the environment for deployment
    environment:
      name: github-pages  # Define the environment (optional)

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Initialize and fetch submodules
          fetch-depth: 0  # To fetch the entire history (optional)
        
      # Step 2: Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Step 3: Upload the site artifact to GitHub Pages
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
